import { IPartialTheme } from "@fluentui/react";

export interface ThemeObject {
  name: string;
  theme: IPartialTheme;
}

export const themes: ThemeObject[] = [
  {
    /** teams default theme */
    name: "Teams Default",
    theme: {
      palette: {
        themePrimary: "#464775",
        themeLighterAlt: "#f6f6f9",
        themeLighter: "#dadae9",
        themeLight: "#bcbcd6",
        themeTertiary: "#8384ac",
        themeSecondary: "#575886",
        themeDarkAlt: "#3f406a",
        themeDark: "#353659",
        themeDarker: "#272842",
        neutralLighterAlt: "#faf9f8",
        neutralLighter: "#f3f2f1",
        neutralLight: "#edebe9",
        neutralQuaternaryAlt: "#e1dfdd",
        neutralQuaternary: "#d0d0d0",
        neutralTertiaryAlt: "#c8c6c4",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#000000",
        white: "#ffffff",
      },
    },
  },
  {
    /** teams dark theme */
    name: "Teams Dark",
    theme: {
      palette: {
        themePrimary: "#a6a7dc",
        themeLighterAlt: "#070709",
        themeLighter: "#1a1a23",
        themeLight: "#313242",
        themeTertiary: "#636384",
        themeSecondary: "#9192c1",
        themeDarkAlt: "#adaedf",
        themeDark: "#b9b9e4",
        themeDarker: "#cacbeb",
        neutralLighterAlt: "#3c3c3c",
        neutralLighter: "#444444",
        neutralLight: "#515151",
        neutralQuaternaryAlt: "#595959",
        neutralQuaternary: "#5f5f5f",
        neutralTertiaryAlt: "#7a7a7a",
        neutralTertiary: "#c8c8c8",
        neutralSecondary: "#d0d0d0",
        neutralPrimaryAlt: "#dadada",
        neutralPrimary: "#ffffff",
        neutralDark: "#f4f4f4",
        black: "#f8f8f8",
        white: "#333333",
      },
    },
  },
  {
    /** teams contrast theme */
    name: "Teams Contrast",
    theme: {
      palette: {
        themePrimary: "#ffff01",
        themeLighterAlt: "#0a0a00",
        themeLighter: "#292900",
        themeLight: "#4d4d00",
        themeTertiary: "#999900",
        themeSecondary: "#e0e000",
        themeDarkAlt: "#ffff19",
        themeDark: "#ffff3d",
        themeDarker: "#ffff70",
        neutralLighterAlt: "#000000",
        neutralLighter: "#000000",
        neutralLight: "#000000",
        neutralQuaternaryAlt: "#000000",
        neutralQuaternary: "#000000",
        neutralTertiaryAlt: "#000000",
        neutralTertiary: "#4d4d00",
        neutralSecondary: "#999900",
        neutralPrimaryAlt: "#e0e000",
        neutralPrimary: "#ffff01",
        neutralDark: "#ffff3d",
        black: "#ffff70",
        white: "#000000",
      },
    },
  },
  {
    name: "ISE AG Light",
    theme: {
      palette: {
        themePrimary: "#a12967",
        themeLighterAlt: "#fbf4f8",
        themeLighter: "#f0d3e2",
        themeLight: "#e3b0ca",
        themeTertiary: "#c66d9b",
        themeSecondary: "#ac3a75",
        themeDarkAlt: "#91245c",
        themeDark: "#7a1f4e",
        themeDarker: "#5a1639",
        neutralLighterAlt: "#faf9f8",
        neutralLighter: "#f3f2f1",
        neutralLight: "#edebe9",
        neutralQuaternaryAlt: "#e1dfdd",
        neutralQuaternary: "#d0d0d0",
        neutralTertiaryAlt: "#c8c6c4",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#000000",
        white: "#ffffff",
      },
    },
  },
  {
    name: "ISE AG Dark",
    theme: {
      palette: {
        themePrimary: "#ff99ce",
        themeLighterAlt: "#0a0608",
        themeLighter: "#291821",
        themeLight: "#4d2e3e",
        themeTertiary: "#995c7b",
        themeSecondary: "#e087b5",
        themeDarkAlt: "#ffa3d3",
        themeDark: "#ffb1da",
        themeDarker: "#ffc6e3",
        neutralLighterAlt: "#3c3b39",
        neutralLighter: "#444241",
        neutralLight: "#514f4e",
        neutralQuaternaryAlt: "#595756",
        neutralQuaternary: "#5f5e5c",
        neutralTertiaryAlt: "#7a7977",
        neutralTertiary: "#c8c8c8",
        neutralSecondary: "#d0d0d0",
        neutralPrimaryAlt: "#dadada",
        neutralPrimary: "#ffffff",
        neutralDark: "#f4f4f4",
        black: "#f8f8f8",
        white: "#323130",
      },
    },
  },
];
